_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.3
            "5": 0.19.4
            "6": 4.48.0
            "8":
                - 2
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 10
learning_rate:
    value: 1e-05
model:
    value: BERT + ResNet50
